import Head from 'next/head';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contacto</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Contacto</h1>
    </>
  );
}
